# Generated by Django 4.2.7 on 2025-02-25 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='حساب_تجاري',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('رقم_الحساب', models.CharField(max_length=50, unique=True)),
                ('نوع_الحساب', models.CharField(max_length=50)),
                ('الاسم', models.CharField(max_length=100)),
                ('اللقب', models.CharField(max_length=100)),
                ('العنوان', models.CharField(max_length=255)),
                ('تاريخ_الميلاد', models.DateField()),
                ('الرصيد_المالي', models.DecimalField(decimal_places=2, max_digits=15)),
                ('عدد_مرات_التحويل', models.IntegerField(default=0)),
                ('رابط_الإحالة', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
