# Generated by Django 4.2.7 on 2025-03-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccp_number', models.CharField(max_length=20, unique=True, verbose_name='رقم CCP')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('last_name', models.CharField(max_length=100, verbose_name='اللقب')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المراد تحويله')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
        ),
    ]
