# Generated by Django 4.2.7 on 2025-03-07 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_profile_delete_businessaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='الملف_الشخصي',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('رقم_الحساب', models.CharField(max_length=50, unique=True)),
                ('نوع_الحساب', models.CharField(max_length=50)),
                ('الاسم_الأول', models.CharField(max_length=100)),
                ('اللقب', models.CharField(max_length=100)),
                ('العنوان', models.CharField(max_length=255)),
                ('تاريخ_الميلاد', models.DateField()),
                ('الرصيد', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('عدد_التحويلات', models.IntegerField(default=0)),
                ('رابط_الإحالة', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('المستخدم', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='الملف_الشخصي', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
