# Generated by Django 5.0.6 on 2024-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_remove_formation_title_formation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='formation',
            name='link',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
