# Generated by Django 5.0.6 on 2024-06-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0004_rename_name_formation_name_formation_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='user',
        ),
    ]
