# Generated by Django 5.0.6 on 2024-06-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_remove_formation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='link',
        ),
    ]
