# Generated by Django 5.0.7 on 2024-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0008_formation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='category',
            field=models.CharField(choices=[('ابتداءي ', 'إبتدائي'), ('متوسطة', 'متوسط'), ('ثانوي', 'ثانوي'), ('جامعة', 'جامعة'), ('المتجر', 'المتجر'), ('دورات متنوعة', 'متنوعةدورات')], max_length=60),
        ),
    ]
