# Generated by Django 5.0.6 on 2024-06-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0006_remove_formation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='link',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
